{{- $genericValues := index .Values "generic-service" -}}
{{- if and .Values.rateLimitingIngress.enabled $genericValues $genericValues.ingress.enabled }}

{{- $generic := dict
  "Chart" ((index .Subcharts "generic-service").Chart)
  "Values" $genericValues
  "Release" .Release
  "Capabilities" .Capabilities
  "Files" .Files
  "Template" .Template
-}}

{{- $fullName := include "generic-service.fullname" $generic -}}
{{- $ingressName := printf "%s-rate-limiting-v1-2" $fullName -}}
{{- $svcPort := $genericValues.service.port -}}
{{- $hosts := or $genericValues.ingress.hosts (list $genericValues.ingress.host) -}}
{{- $paths := .Values.rateLimitingIngress.paths | default (list) -}}

{{- if $paths }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
      {{- $genericWithParentChart := merge (dict "Chart" .Chart) $generic -}}
      {{ include "generic-service.labels" $genericWithParentChart | nindent 4 }}
  annotations:
    {{- with .Values.rateLimitingIngress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $genericValues.allowlist }}
    {{- include "app.makeIpAllowList" $generic | nindent 4 }}
    {{- end }}
    external-dns.alpha.kubernetes.io/set-identifier: {{ $ingressName }}-{{ .Release.Namespace }}-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"

spec:
  {{- with .Values.rateLimitingIngress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        {{- range $hosts }}
        - {{ . }}
        {{- end }}
      {{- if $genericValues.ingress.tlsSecretName }}
      secretName: {{ $genericValues.ingress.tlsSecretName }}
      {{- end }}

  rules:
    {{- range $host := $hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{- range $path := $paths }}
          - path: {{ $path }}
            pathType: Exact
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}

{{- end }}
{{- end }}