services:

  manage-users-db:
    image: postgres:18
    networks:
      - hmpps
    container_name: manage-users-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=manage-users-db

  localstack:
    image: localstack/localstack:4
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
      - 8999:8080
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
