server:
  shutdown: immediate
  port: 9091

api:
  base:
    url:
      oauth: http://localhost:9090/auth
      nomis: http://localhost:8082

notification:
  banner:
    roles: Local Role page message
    search:
