---
# Per environment values which override defaults in hmpps-manage-users-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-users-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_ENDPOINT_URL: http://hmpps-auth.hmpps-auth-dev.svc.cluster.local/auth
    HMPPS_AUTHORIZATION_SERVER_ENDPOINT_URL: https://authorization-server-dev.hmpps.service.justice.gov.uk
    HMPPS_AUTH_EXTERNAL_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    NOMIS_ENDPOINT_URL: https://nomis-user-dev.aks-dev-1.studio-hosting.service.justice.gov.uk
    EXTERNAL_USERS_ENDPOINT_URL: https://external-users-api-dev.hmpps.service.justice.gov.uk
    DELIUS_ENDPOINT_URL: https://community-api-secure.test.delius.probation.hmpps.dsd.io
    BANNER_ROLES:
    BANNER_EMPTY:
    BANNER_DPSMENU:

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
