---
# Per environment values which override defaults in hmpps-manage-users-api/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: manage-users-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_NOMIS: https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk
    API_BASE_URL_EXTERNAL: https://external-users-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_DELIUS: https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io
    HMPPS_AUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    NOMIS_ENDPOINT_URL: https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk
    EXTERNAL_USERS_ENDPOINT_URL: https://external-users-api-preprod.hmpps.service.justice.gov.uk
    DELIUS_ENDPOINT_URL: https://community-api-secure.pre-prod.delius.probation.hmpps.dsd.io
    BANNER_ROLES:
    BANNER_EMPTY:
    BANNER_DPSMENU:

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
