---
# Per environment values which override defaults in hmpps-manage-users-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-users-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_NOMIS: https://nomis-user-dev.aks-dev-1.studio-hosting.service.justice.gov.uk
    BANNER_ROLES:
    BANNER_EMPTY:
    BANNER_DPSMENU:

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
