# Per environment values which override defaults in hmpps-manage-users-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-users-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_ENDPOINT_URL: http://hmpps-auth.hmpps-auth-preprod.svc.cluster.local/auth
    AUTHORIZATION_SERVER_TOKEN_ENDPOINT_URL: http://hmpps-auth.hmpps-auth-preprod.svc.cluster.local/auth/oauth/token
    HMPPS_AUTH_EXTERNAL_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    NOMIS_ENDPOINT_URL: https://nomis-user-pp.aks-live-1.studio-hosting.service.justice.gov.uk
    EXTERNAL_USERS_ENDPOINT_URL: https://external-users-api-preprod.hmpps.service.justice.gov.uk
    DELIUS_ENDPOINT_URL: https://hmpps-auth-and-delius-preprod.hmpps.service.justice.gov.uk
    BANNER_ROLES:
    BANNER_EMPTY:
    BANNER_DPSMENU:


  allowlist:
    undefined: 51.140.210.98/32
    groups: []

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
